<!DOCTYPE html>
<html>
    <head>
        <title>Кристинопіл</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="shortcut icon" type="image/png" href="app/view/images/logo.png"/>

        <link rel="stylesheet" href="app/view/styles/reset.css">
        <link rel="stylesheet" href="app/view/styles/Falcon/style.css">
        <link rel="stylesheet" href="app/view/styles/Falcon/style_max_600px.css">
        <link rel="stylesheet" href="app/view/styles/Falcon/style_min_600px.css">
        <link rel="stylesheet" href="app/view/styles/Falcon/style_min_768px.css">
        <link rel="stylesheet" href="app/view/styles/Falcon/style_min_992px.css">
        <link rel="stylesheet" href="app/view/styles/Falcon/style_min_1200px.css">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            $(document).ready(function(){
            $("#char").hide();
            $("#opis").show();
            $("#ukr").hide();
                
            $("#img_1").show();
            $("#img_2").hide();
            $("#img_3").hide();
            $("#img_4").hide();
            $("#img_5").hide();
            $("#img_6").hide();
            $("#img_7").hide();
            $("#img_8").hide();
            $("#img_9").hide();
            $("#img_10").hide();
                
                $("#but_opis").click(function(){
                    $("#char").hide();
                    $("#opis").show();
              });
                $("#but_char").click(function(){
                    $("#char").show();
                    $("#opis").hide();
              });
                $("#but_ukr").click(function(){
                    $("#np").show();
                    $("#ukr").hide();
              });
                $("#but_np").click(function(){
                    $("#ukr").show();
                    $("#np").hide();
              });
                $("#but_img_1").click(function(){
                    $("#img_1").show();
                    $("#img_2").hide();
                    $("#img_3").hide();
                    $("#img_4").hide();
                    $("#img_5").hide();
                    $("#img_6").hide();
                    $("#img_7").hide();
                    $("#img_8").hide();
                    $("#img_9").hide();
                    $("#img_10").hide();
              });
                $("#but_img_2").click(function(){
                    $("#img_2").show();
                    $("#img_1").hide();
                    $("#img_3").hide();
                    $("#img_4").hide();
                    $("#img_5").hide();
                    $("#img_6").hide();
                    $("#img_7").hide();
                    $("#img_8").hide();
                    $("#img_9").hide();
                    $("#img_10").hide();
              });
                $("#but_img_3").click(function(){
                    $("#img_3").show();
                    $("#img_2").hide();
                    $("#img_1").hide();
                    $("#img_4").hide();
                    $("#img_5").hide();
                    $("#img_6").hide();
                    $("#img_7").hide();
                    $("#img_8").hide();
                    $("#img_9").hide();
                    $("#img_10").hide();
              });
                $("#but_img_4").click(function(){
                    $("#img_4").show();
                    $("#img_2").hide();
                    $("#img_3").hide();
                    $("#img_1").hide();
                    $("#img_5").hide();
                    $("#img_6").hide();
                    $("#img_7").hide();
                    $("#img_8").hide();
                    $("#img_9").hide();
                    $("#img_10").hide();
              });
                $("#but_img_5").click(function(){
                    $("#img_5").show();
                    $("#img_2").hide();
                    $("#img_3").hide();
                    $("#img_4").hide();
                    $("#img_1").hide();
                    $("#img_6").hide();
                    $("#img_7").hide();
                    $("#img_8").hide();
                    $("#img_9").hide();
                    $("#img_10").hide();
              });
                $("#but_img_6").click(function(){
                    $("#img_6").show();
                    $("#img_2").hide();
                    $("#img_3").hide();
                    $("#img_4").hide();
                    $("#img_5").hide();
                    $("#img_1").hide();
                    $("#img_7").hide();
                    $("#img_8").hide();
                    $("#img_9").hide();
                    $("#img_10").hide();
              });
                $("#but_img_7").click(function(){
                    $("#img_7").show();
                    $("#img_2").hide();
                    $("#img_3").hide();
                    $("#img_4").hide();
                    $("#img_5").hide();
                    $("#img_6").hide();
                    $("#img_1").hide();
                    $("#img_8").hide();
                    $("#img_9").hide();
                    $("#img_10").hide();
              });
                $("#but_img_8").click(function(){
                    $("#img_8").show();
                    $("#img_2").hide();
                    $("#img_3").hide();
                    $("#img_4").hide();
                    $("#img_5").hide();
                    $("#img_6").hide();
                    $("#img_7").hide();
                    $("#img_1").hide();
                    $("#img_9").hide();
                    $("#img_10").hide();
              });
                $("#but_img_9").click(function(){
                    $("#img_9").show();
                    $("#img_2").hide();
                    $("#img_3").hide();
                    $("#img_4").hide();
                    $("#img_5").hide();
                    $("#img_6").hide();
                    $("#img_7").hide();
                    $("#img_8").hide();
                    $("#img_1").hide();
                    $("#img_10").hide();
              });
                $("#but_img_10").click(function(){
                    $("#img_10").show();
                    $("#img_2").hide();
                    $("#img_3").hide();
                    $("#img_4").hide();
                    $("#img_5").hide();
                    $("#img_6").hide();
                    $("#img_7").hide();
                    $("#img_8").hide();
                    $("#img_9").hide();
                    $("#img_1").hide();
              });
            });
        </script>
    </head>
    <body>
        <header>
            <div id="head">
                <img src="app/view/images/logo.png">
                <article>
                    <h1>Кристинопіль</h1>
                    <span>Наш товар за справедливу ціну</span>
                </article>
            </div>
            <div id="name_adm">
                <?php
                if(isset($_SESSION['adm'])){
                    $select = $Admin -> select_adm_id($pdo, $_SESSION['adm']);
                    foreach($select as $sel){
                        echo "<p>Ваш ід: ".$sel['id_adm']."</p> <h3>".$sel['surname']." ".$sel['name']."</h3>";
                    } 
                }
                ?>
            </div>
            <br class="cls">
        </header>
