<div id="typ" class="window">
    <form method="get" action="">
        <input type="hidden" name="controller" value="Falcon">
        <input type="hidden" name="action" value="zalogowany">
        <input type="hidden" name="window" value="1">
        
        <label class="winlabel"><p>Тип:          </p><select type="text" name="typ">
            <option>Виберіть тип продукту</option>
         <?php
            $select = $Admin -> select_typ($pdo);
            foreach($select as $sel){ if($sel['id_typ'] != 1000){
                    ?><option value="<?php echo $sel['id_typ']; ?>"><?php echo $sel['name_typ']; ?></option> <?php } } ?>
            
        </select></label>
        
        <input type="hidden" name="menu" value="1">
        <button class="winbut" type="submit">ОК</button>
    </form>
</div>