<div id="foo"></div>
    <footer>
        <div id="footer">
            <a href="https://krystynopil.biz.ua/">
                <img class="foot_logo" src="app\view\images\logo.png">
            </a>
            <div id="foot_text">
                <p>&copy;Кристинопіль</p>
                <h4>Контакти:</h4>
                <ul>тел. +380933695259</ul>
                <ul>Email: Krystynopil2021@gmail.com</ul>
            </div>
            <a href="https://www.instagram.com/krystynopil_2021">
                <img class="foot_soc" src="app\view\images\ins.png">
            </a>
            <a href="https://www.facebook.com/%D0%86%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%9A%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%BD%D0%BE%D0%BF%D1%96%D0%BB%D1%8C-103629771815201">
                <img class="foot_soc" src="app\view\images\fac.png">
            </a>
            <br class="cls">
        </div>
    </footer>
    </body>
</html>